config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    return false unless request.session[:user_id]
    user = User.find(request.session[:user_id])
    user && user.admin?
  end
end

Rails.application.routes.draw do
  root to: 'questions#index'

  # Question URLs
  get '/ask', to: 'questions#new', as: 'new_question'
  get '/questions/new' => redirect('/ask')
  get '/questions/tagged/:tag', to: 'questions#tagged', as: 'questions_tagged'
  resources :questions, only: [:create, :show]

  # Shorter URLs where slugs don't matter
  patch '/q/:id', to: 'questions#update', as: 'update_question'
  get '/q/:id/edit', to: 'questions#edit', as: 'edit_question'
  get '/q/:id/timeline', to: 'questions#timeline', as: 'question_timeline'
  post '/q/:id/accept', to: 'questions#accept_answer', as: 'accept_answer'
  post '/q/:id/unaccept', to: 'questions#unaccept_answer', as: 'unaccept_answer'

  resources :answers, only: [:create, :edit, :update]
  get '/a/:id/timeline', to: 'answers#timeline', as: 'answer_timeline'

  resources :badges, only: [:show]
  resources :comments, only: [:new, :create]
  resources :votes, only: [:create, :destroy]

  get '/user/edit', to: 'users#edit', as: 'edit_user'
  resources :users, only: [:index, :show, :create, :update] do
    member do
      get 'answers'
      get 'questions'
    end
  end
  post '/logout', to: 'sessions#destroy'

  # omniauth callbacks
  get '/auth/:provider/callback', to: 'authorizations#callback'
  post '/auth/:provider/callback', to: 'authorizations#callback'

  get '/tags', to: 'tags#index'
  get '/tags/search', to: 'tags#search'

  constraints AdminConstraint.new do
    namespace :admin do
      resources :users, only: [:edit, :update]
      get '/', to: 'dashboard#index'
      get '/health', to: 'dashboard#health'
    end

    mount PgHero::Engine, at: '/admin/pghero'
    mount Sidekiq::Web, at: '/admin/sidekiq'
  end

  # development routes
  if Rails.env.development?
    get '/dev/login', to: 'dev#login'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:title) %>
      <title><%= %(#{yield(:title)} · #{SiteSettings.name}) %></title>
    <% else %>
      <title><%= SiteSettings.name %></title>
    <% end %>
    <%= stylesheet_link_tag :application %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to SiteSettings.name, '/', class: 'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Tags', tags_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Ask Question', new_question_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><p class="navbar-reputation"><%= current_user.reputation %></p></li>
              <% if current_user.has_gold_badges? %>
                <li><span class="badge-count gold"><%= current_user.gold_count %></span><li>
              <% end %>
              <% if current_user.has_silver_badges? %>
                <li><span class="badge-count silver"><%= current_user.silver_count %></span><li>
              <% end %>
              <% if current_user.has_bronze_badges? %>
                <li><span class="badge-count bronze"><%= current_user.bronze_count %></span><li>
              <% end %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin', '/admin' %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="user-dropdown"><%= current_user.display_name %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Your profile', current_user, tabindex: '-1' %></li>
                  <li><%= link_to 'Edit profile', edit_user_path %></li>
                  <li><%= button_to 'Logout', '/logout', method: :post, id: 'logout' %></li>
                </ul>
              </li>
            <% else %>
              <li><a id="login-link" href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <% if @admin_page_warning %>
     <%= render partial: 'admin/warning' %>
    <% end %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="flash-<%= name %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
    <% unless logged_in? %>
      <%= render partial: 'layouts/login' %>
    <% end %>
  </body>
</html>